# Generated by Django 4.1.7 on 2023-04-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='men',
            old_name='time_upload',
            new_name='time_update',
        ),
    ]
